### ISSUE TITLE
mongodb_version not set on first run

### ISSUE THREAD

**Issue by af6140** [Katello/puppet-pulp#141]
Error: Evaluation Error: Unknown variable: '::mongodb_version'. at /etc/puppet/modules/pulp/manifests/database.pp:4:20 on node centos-6-x64

**Comment by walkamongus** [comment]
I think I just ran into this issue and it created a flapping mongo pidfile and a service restart error.

The code at https://github.com/Katello/puppet-pulp/blob/c0bc48f5c49aa59958b773fb99021500b8529dec/manifests/database.pp#L4-8 uses the mongodb_version fact to set the pidfile path. On the first run, the fact won't be populated and I get  pidfilepath = '/var/run/mongodb/mongodb.pid.

The next run, the fact is populated and my version is > 2.6.5 and I get pidfilepath = '/var/run/mongodb/mongod.pid. The new pidfile path is updated in the config file and created but the service fails to restart because it looks at the pid file specified in the config file (which is different now and doesn't contain the PID of the currently running mongo process).

```
[root@host ~]# facter -p | grep mongodb_version
[root@host ~]# puppet apply -e 'if (versioncmp($::mongodb_version, "2.6.5") >= 0) {$mongodb_pidfilepath = "/var/run/mongodb/mongod.pid"} else {$mongodb_pidfilepath = "/var/run/mongodb/mongodb.pid"}; notify {$mongodb_pidfilepath: }'
Warning: Scope(Class[main]): Could not look up qualified variable '::mongodb_version'; 
Notice: Compiled catalog for host in environment production in 0.43 seconds
Notice: /var/run/mongodb/mongodb.pid
Notice: /Stage[main]/Main/Notify[/var/run/mongodb/mongodb.pid]/message: defined 'message' as '/var/run/mongodb/mongodb.pid'
Notice: Applied catalog in 0.22 seconds
```

**Comment by ekohl** [comment]
https://github.com/Katello/puppet-pulp/commit/897430f74655dc171698cdc825253b3c67989e61 removed the use of this fact.
